apiVersion: v1
kind: Service
metadata:
  name: tf1-ai-engine
  labels:
    app: tf1-ai-engine
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: tf1-ai-engine
  type: ClusterIP
