apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/ai-engine

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: tf1-ai-triage-engine
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1


