apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tf1-namespaces-rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Hung0codon/Trigger_Hub.git
    targetRevision: HEAD
    path: manifests/overlays/sandbox/namespaces-rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
